### ISSUE TITLE
[创建项目]输入框限制内容

### ISSUE THREAD

**Issue by alex-x-crypto** [SeeDAO-OpenSource/combinator-frontend#9]
1. 创建项目时，限制”除Additional Documents外“所有输入框必填
      a. 如果必选项没有填写，会展示红色提醒
3. 限制字数
    a. 项目名称暂定限制20个字符
    b. 项目描述暂定限制2000个字符，高度再高一些，内容多的时候自动调整高度
4. 输入框占位符提示（中英文）
5. 推特简单校验（非中文）
6. 封面图限制 *.png, *.jpg格式
7. 附件限制*.pdf格式（文案对应修改）

**Comment by alex-x-crypto** [comment]
附件变为可选，其他仍然必填

**Comment by zouhangwithsweet** [comment]
Form DEMO：
1. 文件上传的校验；参考下 https://github.com/vueComponent/ant-design-vue/issues/1814#issuecomment-735397551
2. form 表单外边触发校验 参考下 https://ant.design/components/form-cn/#validateFields-%E8%BF%94%E5%9B%9E%E7%A4%BA%E4%BE%8B
